### ISSUE TITLE
Is it supported for React Native Storybook?

### ISSUE THREAD

**Issue by simply-innovative** [Checkfront/react-storybook-addon-chapters#11]
any plans to support the same for rn storybook, if yes what are the timeline for the same?

**Comment by brettgoss** [comment]
With Storybook V6 making this addon obsolete with the addition of built-in [grouping and hierarchy](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy), we don't have any plans to support React Native Storybook ourselves at this time. If anyone is interesting in contributing this support or forking this addon, please feel free.
