### ISSUE TITLE
Allow Use Of Decorators

### ISSUE THREAD

**Issue by PDXIII** [Checkfront/react-storybook-addon-chapters#14]
Hi!
For some of my components I need a dark background. Is it possible to use decorators or anything else, that doesn’t show up in the source area?

**Comment by yangshun** [comment]
Sorry I haven't had the time to write up the documentation for using the decorators and am not very keen on publishing it at the moment... Would you be keen to take that up? I think we can publish a major version bump after we have the documentation for decorators.

**Comment by PDXIII** [comment]
Hi, @yangshun! 
Thank you for your reply. I am not good enough to accomplish that yet. If I figure out how it can work I would like to help you but currently, I just can’t, sorry!

**Comment by PDXIII** [comment]
Hey, @yangshun! While taking a look at your repository and comparing it with the code from your installed node_module a I discovered that they differ very much even they have the same version number. 

I haven’t published anything via npm so I am not familiar if this is like it supposed to be, but in your addon I installed via npm part with the ```SectionDecorator``` is missing completely.

**Comment by yangshun** [comment]
Yes, that's because the decorator PR was landed after I published the latest version. Version bumps only occur before publishing. You can refer to the commit history for reference: https://github.com/yangshun/react-storybook-addon-chapters/commits/master

If you would eagerly like to use the decorator feature, simply install the package via specifying the commit hash instead of a semver version inside your `package.json`:

```
{
  "react-storybook-addon-chapters": "git://github.com/yangshun/react-storybook-addon-chapters.git#db0a5e44d235d07766f1ec7d3dcac32eb1c0f532"
}
```

Let me know if it works!

**Comment by PDXIII** [comment]
Yes, thank you, @yangshun!

I already have done that and it works pretty well. One thing I would like to achieve is to have a decorator just for a particular component. Let’s say I have a component (e.g. button) in different color variations (light & dark). To show these variations I would like to have different background for the component per section.

Is this possible or is this a problem of Storybook in general?

**Comment by yangshun** [comment]
Storybook as it stands doesn't allow much customizaton, hence the existence of this addon. I believe you should be able to achieve what you need with decorators as it enables custom styling.

**Comment by khronedev** [comment]
@PDXIII I don't know if that solves your issue (or after a year you're still looking for one), but I've added functionality to add different decorators for each section component: https://github.com/Checkfront/react-storybook-addon-chapters/pull/40 . You can customize the background and other stuff, while not polluting your code with wrappers or something.

**Comment by PDXIII** [comment]
@khronedev Thanks for letting me know.
