### ISSUE TITLE
Not working with react v16

### ISSUE THREAD

**Issue by ducarroz** [Checkfront/react-storybook-addon-chapters#16]
I am trying to update my project to react v16 but I am getting an JS error at

https://github.com/yangshun/react-storybook-addon-chapters/blob/master/src/components/PropTable.jsx#L105

```js
PropTable.propTypes = {
  type: React.PropTypes.func,
};
```
React.PropTypes is undefined, sound line https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by ducarroz** [comment]
There is also issue with `React.createClass` which I presume is gone in react v16.

**Comment by brandonellis** [comment]
Just want to point out that the NPM version has not been updated to reflect these changes.  I would say that the package.json file needs a version bump or npm needs to be notified of the latest fix.

**Comment by brandonellis** [comment]
I have a PR open for most of the updated dependencies needed for this to work correctly.  I also refactored the code a little.  Waiting for maintainer status.

**Comment by brandonellis** [comment]
@ducarroz master branch should be able to handle all of your React 16 issues.

**Comment by ducarroz** [comment]
can somebody with the proper permission push the latest version to the npm registry?

**Comment by brandonellis** [comment]
Working through that today hopefully @ducarroz

**Comment by ducarroz** [comment]
thanks!
