### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by yangshun** [Checkfront/react-storybook-addon-chapters#17]
I don't really use storybook anymore and don't have much interest or motivation in maintaining it. If anyone would like to be a maintainer please comment below!

**Comment by brandonellis** [comment]
Sure, I forked and created a PR for updating most of the dependencies.  Please approve.

**Comment by yangshun** [comment]
Can you pass me your npm username? Going to add you in so that you have publishing rights

**Comment by yangshun** [comment]
> How do you feel of just updating the readme after the PR is merged to state its EOL?

Sorry I don't understand. EOL = End of life?

> We can point it to the new repo like the other passed off repo's.

Is there a new repo to be created?

**Comment by brandonellis** [comment]
Yup, EOL means End of Life. I currently have it forked (though consistent with the PR open).  I can create it as a new repo if that's the easiest route.

**Comment by henningmu** [comment]
Just thinking out loud here: Maybe it's an option to move this repo in the main mono-repo of storybooks where most of the other addons live, too?
Nevertheless, watching the process of how you decide to move on.

@yangshun Thanks a ton for having build this awesome piece of software. Much appreciated ❤️

**Comment by egeriis** [comment]
@brandonellis @yangshun Thank you for maintaining and creating this lib. Could I call for attention that it would be best served for the users of this lib, if we don't have to update our dependencies to a fork? Should be straightforward to move ownership, if that's the direction you want to take this 🙂

**Comment by brandonellis** [comment]
@henningmu Good suggestion, what's the process there? do you know what it is?

@egeriis Yes, I would prefer to just changed ownership. That is a good point. 

@yangshun I am using my repo in my project at the moment.  When can you do the ownership change?

**Comment by yangshun** [comment]
I second @henningmu 's suggestion. I think we can file a PR at the main storybook repo to move this repo into https://github.com/storybooks/storybook/tree/master/addons. I'd say this is the recommended way as the storybook maintainers can update all addon versions as they release new versions of the core storybook. What do you say @brandonellis ? Do you want to take charge of this?

**Comment by yangshun** [comment]
There might be an issue because there is another storybook chapters addon and it has taken the namespace `storybook/addon-chapters`.

https://github.com/sm-react/storybook-chapters/issues/4

**Comment by yangshun** [comment]
Also, I'm very curious why there are so many downloads for this library on npm -
 https://www.npmjs.com/package/react-storybook-addon-chapters:

> 14,518 downloads in the last day
> 70,316 downloads in the last week
> 187,536 downloads in the last month

Seems out of the ordinary for an addon. Does anyone know which organization is using this such that it sees such relatively high usage? Probably the ownership can be transferred to them since they are a heavy user of it.

**Comment by brandonellis** [comment]
Those numbers seem very high, although it is probably my company.  We are in the midst of creating a design system and going to rely on this add-on specifically.

**Comment by yangshun** [comment]
@brandonellis Since your company heavily relies on it, I can transfer the repository to you. How do you want to do this?

**Comment by brandonellis** [comment]
Since there is a collision in names with the main storybook repo -- I would just transfer ownership to me.  I can take care of the rest when we have time to manage it.  I have a few others who will pop in and out of the maintenance of the add-on.

**Comment by brandonellis** [comment]
Any updates for me @yangshun ?

**Comment by yangshun** [comment]
I can't transfer ownership since you still have a forked version of the repo on your account

**Comment by brandonellis** [comment]
https://github.com/Checkfront

**Comment by yangshun** [comment]
I don't have permissions to create repos on that organization. Perhaps you can do it? I added you as collaborator to this repository a while back.

**Comment by brandonellis** [comment]
I've created the repository.  https://github.com/Checkfront/react-storybook-addon-chapters

I don't seem to have sufficient permissions to this repo to initiate the transfer.

**Comment by yangshun** [comment]
Few ways:

1. Add me to the organization temporarily with create repo permissions, after I transfer, you can remove me. 
2. Just use a new repository and lose the issues/PRs. I think that's also ok considering not too many issues here.

**Comment by brandonellis** [comment]
Ah, I missed the import step on my end.  I imported based on this repo's url.  Commit history is intact without issues or any PR's which isn't an issue.

**Comment by yangshun** [comment]
Ok then I'll start changing all url to refer to `https://github.com/Checkfront/react-storybook-addon-chapters` instead. I can (manually) migrate the existing issues there as well. How does that sound?

**Comment by brandonellis** [comment]
Works for me.  Thanks for the help.

**Comment by egeriis** [comment]
@yangshun If you add @brandonellis as a repo admin, he can transfer

**Comment by yangshun** [comment]
I have invited but @brandonellis has yet to accept the invitation. Anyway I don't think collaborators can move repos. Only owners can. I just thought of an idea. I'll create an organization, add @brandonellis as the owner of the org, shift the repo into the organization and then he can move it to his organization

**Comment by yangshun** [comment]
@brandonellis I have added you to this organization. Once you accept the invitation link, I'll change your role to Owner and you should be able to do the transfer 👌

**Comment by brandonellis** [comment]
I have accepted.  Let me know when you change the role and ill handle the transfer.  Thanks @yangshun

**Comment by yangshun** [comment]
@brandonellis Done! You have owner rights now

**Comment by brandonellis** [comment]
All transferred.  @yangshun - Were you able to add the publishing rights to npm?

**Comment by yangshun** [comment]
I have done so: https://www.npmjs.com/package/react-storybook-addon-chapters

**Comment by brandonellis** [comment]
Great.  Thanks again for the help and your contribution.

**Comment by yangshun** [comment]
Awesome! You might also want to make a PR to change the gallery URL to the current one - https://storybook.js.org/addons/addon-gallery/

**Comment by brandonellis** [comment]
It seems to have automagically handled that with the transfer. 👍

**Comment by yangshun** [comment]
GitHub is doing a redirect but I think it's still better to change it within the Storybook website source.
