### ISSUE TITLE
React v16 still not supported?

### ISSUE THREAD

**Issue by ngbrown** [Checkfront/react-storybook-addon-chapters#19]
Based on the closed issue, #16, I thought React v16 was supported, but I just received the following exception when trying to start storybook after installing `react-storybook-addon-chapters` v2.0.0 from npm:

```
ERROR in ./node_modules/markdown-to-react-components/src/CodeComponent.js
Module not found: Error: Can't resolve 'create-react-class' in 'D:\dev\H-D\revival-tis\te-revival\node_modules\markdown-to-react-components\src'
 @ ./node_modules/markdown-to-react-components/src/CodeComponent.js 2:23-52
 @ ./node_modules/markdown-to-react-components/src/index.js
 @ ./node_modules/react-storybook-addon-chapters/dist/utils/info-content.js
 @ ./node_modules/react-storybook-addon-chapters/dist/components/Story.js
 @ ./node_modules/react-storybook-addon-chapters/dist/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
```

It appears that `markdown-to-react-components` hasn't been supporting [React since 15.6.1](https://github.com/christianalfoni/markdown-to-react-components/pull/27) and [Marksy](https://github.com/cerebral/marksy) is the replacement.

`@storybook/react` is v3.2.14.

**Comment by ngbrown** [comment]
**Update**: I can add `create-react-class` as a peer dependency, but that's not ideal since it's depreciated.  Can the markdown component be switched to Marksy?

**Comment by brandonellis** [comment]
Yup, should have caused any install errors as the package.json is referencing a specific hash in the repo which was still working with react 16.  It's one of the last upgrades to swap over.

**Comment by brandonellis** [comment]
@ngbrown Recent release should take care of your problems.  Migrated to 'marksy' repo and fixed the markdown issues.
