### ISSUE TITLE
Add option to disable default section styles

### ISSUE THREAD

**Issue by zerodexter82** [Checkfront/react-storybook-addon-chapters#22]
I'm having a bit of a hard time overriding the section styles that are injected by this addon (e.g. margins, font family, font sizes,...).

Is there currently a way to disable those or could this be added in a future version?

**Comment by brandonellis** [comment]
Can you guys provide so more information or examples of how you are applying your styles and what you are having difficulty overwriting?

**Comment by zerodexter82** [comment]
For example div and heading styles:

`<div style="margin-bottom: 60px;"><div><h3 style="color: rgb(54, 58, 69); font-size: 24px; margin-bottom: 10px;">Headings</h3></div></div>`

Among other things we're using storybook as a sort-of styleguide for headings and other elements, which get overwritten by the inline styles.

**Comment by johnnyBira** [comment]
Any news on this one?

**Comment by gael-boyenval** [comment]
+1

**Comment by brandonellis** [comment]
I have a branch in progress.  Essentially, I am just going to strip out the default styling and apply consistent classes to each block.  This will allow each user to apply their own styles in their own stories.

**Comment by brandonellis** [comment]
PR is open.  Removes inline styles and adds classes to the rendered components of the Chapters Add-on.  Branch name is defaultStyles if you wanted an early peek.

**Comment by cmalven** [comment]
The entire point of storybook is to accurately preview components. The fact that this add-on automatically adds styles that affect the appearance of _all_ component text and can't easily be removed is a big deal. Looking forward to a fix for this.

**Comment by brandonellis** [comment]
It's been added.  The latest version increase contains what is needed.  It's in the README.md file. 

`To turn off the default styles add:

setDefaults({sectionOptions: {useTheme: false}});

All rendered components have a specified class. With the 'useTheme' set to false you should have no problem styling your chapters.`

**Comment by cmalven** [comment]
Thank you @brandonellis!
