### ISSUE TITLE
'setDefaults' is not a function

### ISSUE THREAD

**Issue by krs-10** [Checkfront/react-storybook-addon-chapters#23]
I'm getting the following error with the latest version from npm (2.1.0):

`Uncaught TypeError: (0 , _reactStorybookAddonChapters.setDefaults) is not a function`

Double-checking in RunKit: 
<img width="910" alt="screen shot 2017-12-09 at 3 04 54 pm" src="https://user-images.githubusercontent.com/33099338/33800323-7198f9c0-dcf2-11e7-93ab-133cea361e1e.png">

Could you publish your latest release? Thanks!

**Comment by brandonellis** [comment]
The latest release is published. (2.1.0). Are you able to provide anymore information on how you are triggering this?

**Comment by krs-10** [comment]
I'm using the exact same approach described for the 'Global options' section of the documentation: https://github.com/Checkfront/react-storybook-addon-chapters#global-options

Sorry for referring to the latest version, I meant to say the latest commit: https://github.com/Checkfront/react-storybook-addon-chapters/commit/bcab34b3a596aa66e324a4e4f1a62319e8c1b4aa. 

I think the issues are that the 'dist' folder wasn't rebuilt and included in https://github.com/Checkfront/react-storybook-addon-chapters/commit/bcab34b3a596aa66e324a4e4f1a62319e8c1b4aa, and the npm package hasn't been updated to reflect that commit. 

Apologies if I'm doing something wrong on my end!

**Comment by brandonellis** [comment]
Ah, yes.  Missed that one.  2.1.1 is now published.

**Comment by krs-10** [comment]
Looks resolved to me; thank you!
