### ISSUE TITLE
Remove story title from preview

### ISSUE THREAD

**Issue by vuongc** [Checkfront/react-storybook-addon-chapters#24]
The behavior is not the same as the default `.add` from storybook, I would prefer to choose my own preview and not being forced to use the story tab name as title. Will it be possible to remove this behavior in the futur ?

**Comment by hyfer** [comment]
Any news about this?

**Comment by brandonellis** [comment]
At the moment we have not had a chance to look into the issue that has been explained.  However, we welcome a pull request that we can review if you are interested in contributing.

**Comment by brettgoss** [comment]
With Storybook V6 making this addon obsolete with the addition of built-in [grouping and hierarchy](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy), we don't have any plans to continue to add features or make changes to this addon.
