### ISSUE TITLE
Support additional line breaks or paragraphs in markdown

### ISSUE THREAD

**Issue by zarjay** [Checkfront/react-storybook-addon-chapters#25]
How can I add paragraphs or additional line breaks to the info sections? I can't reproduce what's in the [demo](http://checkfront.github.io/react-storybook-addon-chapters/?selectedKind=Addon%20Chapters&selectedStory=Story%20With%20Chapters&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel), even when I clone the project and run it locally:

<img width="1305" alt="screen shot 2018-01-10 at 8 51 25 pm" src="https://user-images.githubusercontent.com/679049/34806470-b9daf44e-f648-11e7-86ac-cd3cea847ccb.png">

**Comment by brandonellis** [comment]
I removed the default styling that was pulling in from another add-on.  You may need to style your P tags the way you want but the proper line spacing is now taking place.
