### ISSUE TITLE
Support functions to create configuration objects

### ISSUE THREAD

**Issue by at0g** [Checkfront/react-storybook-addon-chapters#27]
It would be useful to have a function instead of a static object when configuring `addWithChapters`.

eg.
```
.addWithChapters('as a function', () => ({
   chapters: {...}
}))
```

Are you open to a PR adding this functionality?

**Comment by brandonellis** [comment]
Always, we encourage it.

**Comment by at0g** [comment]
Cheers - PR here: #28

**Comment by brandonellis** [comment]
Awesome, thanks @at0g will take a look early this week.  Thanks!
