### ISSUE TITLE
Markdown code block

### ISSUE THREAD

**Issue by johnnyBira** [Checkfront/react-storybook-addon-chapters#30]
Hi!

I'm trying to add a code block in markdown format as part of my info string. I've managed to format the string in such a way that it outputs the desired `<code />` and `<pre />` elements. The `<code />` element has the class attribute `hljs javascript`.
`<code class="hljs javascript" >`

My only problem now is the color formatting of the code block. I noticed your using `marksy` to compile the string from markdown to html, so I followed their instructions under [Code highlighting](https://www.npmjs.com/package/marksy#code-highlighting) and managed to get part of the styling working by loading some additional CSS (basically just the container for the code block).

Can you recommend a way to get this working?

Thank you,
/John

**Comment by brandonellis** [comment]
Hey John,

I don't have any recommendations at the moment, we just recently switched to the new marksy dependency as the previous dependency (cant remember the name) was deprecated and no longer working with the new React versions.
