### ISSUE TITLE
Markdown misinterpreted 

### ISSUE THREAD

**Issue by johnnyBira** [Checkfront/react-storybook-addon-chapters#32]
I'm having a hard time wrapping my head around exactly how markdown is parsed inside of chapters. Sometime the output is exactly what you'd expect, but more often than not html is outputted in plain text.
Adding examples in code blocks behave very unreliably as well. Especially describing  React elements, (both inside and out side a code blocks) a lot of times  will be rendered as html element or not visible at all.

Usually I get the best result by having my markdown in separate files, importing them and adding those inside of chapters. But even this doesn't seam to guarantee the resulting markup end up the way it's suppose to.

**Comment by johnnyBira** [comment]
Here's an example of html being generated into plain text:

<img width="779" alt="screen shot 2018-03-09 at 01 22 20" src="https://user-images.githubusercontent.com/23634023/37183855-6bd7c214-2338-11e8-86df-93c08b30db58.png">

A few lines further down, inside the same area of chapters, with identical markdown, it works as expected:
<img width="752" alt="screen shot 2018-03-09 at 01 25 33" src="https://user-images.githubusercontent.com/23634023/37183926-d574e0e4-2338-11e8-946d-3a7c4b47bb38.png">

**Comment by brandonellis** [comment]
Do you have the code block you are using that you can share?  I'd like to look into this for you but I can't get the same result.
