### ISSUE TITLE
return the actual pattern in an Iframe

### ISSUE THREAD

**Issue by gael-boyenval** [Checkfront/react-storybook-addon-chapters#33]
Hi, 
I have problems with styling and customizing chapters.
I think I'm not alone, reading the other issues

- 1 / global styles required for patterns apply to chapter UI
- 2 / can't override chapter UI styles
- 3 / decorators apply to chapters instead of actual patterns

I think the best way to handle that would be to wrap the `sectionsFn` into an Iframe, so the Add-on UI is completely decoupled from the actual Patterns UI. 
It would make it easier to style either add-on UI and pattern. 

Tell me if you think this would be a plausible option, I could help if necessary, but I figured you could easily tell me if it's viable or not.

**Comment by brandonellis** [comment]
I added a setDefaults option to a PR (defaultStyles) I have open.  This allows you to turn off the inline styles and applies classes to all of the rendered components.
