### ISSUE TITLE
Give user ability to not render components

### ISSUE THREAD

**Issue by ryelo** [Checkfront/react-storybook-addon-chapters#37]
Trying to split up sections of components and the source code for those components. Ideally, it would be nice to not actually render the `sectionFn`, but still have the ability to pull the source code from it as some kind of option. 

There's always the ability to hack around it and just target it with css to hide it, but that's obviously not the cleanest solution.

**Comment by brettgoss** [comment]
With Storybook V6 making this addon obsolete with the addition of built-in [grouping and hierarchy](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy), we don't have any plans to continue to add features or make changes to this addon.
