### ISSUE TITLE
Support for flow types

### ISSUE THREAD

**Issue by rebmullin** [Checkfront/react-storybook-addon-chapters#41]
When I use flow in a component, instead of a props table, the output displays the following:

PropTypes
<Badge> Component
No propTypes defined!

Here are some of storybook packages that I have set up:
```javascript
"@storybook/addon-info": "^3.4.11",
"@storybook/addon-options": "^3.4.10",
"@storybook/addons": "^3.4.10",
"@storybook/react": "^3.4.10",
"react-storybook-addon-chapters": "^2.1.7",
```

I don't see any docs about this so I assume it's not supported but wanted to double check this and/or see if this is something that you will be adding in the future?

**Comment by brettgoss** [comment]
With Storybook V6 making this addon obsolete with the addition of built-in [grouping and hierarchy](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy), we don't have any plans to continue to add features to this addon. It also looks as though Storybook itself supports Flow types as of https://github.com/storybookjs/storybook/pull/4971
