### ISSUE TITLE
TypeError when rendering the source of a section with a Fragment as a prop

### ISSUE THREAD

**Issue by atomanyih** [Checkfront/react-storybook-addon-chapters#43]
Running the following example:

```jsx
const SomeComponent = ({someProp}) => (
  <div>
    {someProp}
  </div>
);

storiesOf('Components', module)
  .addWithChapters(
    'Fragment',
    {
      chapters: [
        {
          sections: [
            {
              title: 'I will error',
              sectionFn: () => (
                <SomeComponent someProp={
                  <React.Fragment>
                    <div>Hi</div>
                    <div>Hello</div>
                  </React.Fragment>
                }/>
              )
            }
          ]
        }
      ]
    }
  );
```

Renders this error:

![image](https://user-images.githubusercontent.com/2305345/47824299-70c29c80-dd29-11e8-83a0-88b70df8f082.png)

Other info:
- If the `Fragment` is passed in as `children`, it renders the source fine except the fragment shows up as `<Unknown>`
- If `showSource` is `false`, there is no error

**Comment by alienfacepalm** [comment]
I've seen this exact same issue in `withInfo` when using @emotion components, so since this is a fork, it's probably inherited from `withInfo`.
