### ISSUE TITLE
Bug: Maximum callstack exceeded

### ISSUE THREAD

**Issue by stephanschubert** [Checkfront/react-storybook-addon-chapters#45]
There's an [infinite loop](https://github.com/Checkfront/react-storybook-addon-chapters/blob/master/src/components/Section.jsx#L223-L243) because `extract` does  not accept the next level's `children` as argument but uses the ones from the upper scope.

**Comment by brandonellis** [comment]
@stephanschubert 3.0.1 should fix this for you.
