### ISSUE TITLE
Bug: Rendering of `PropTable`

### ISSUE THREAD

**Issue by stephanschubert** [Checkfront/react-storybook-addon-chapters#46]
I found 2 issues:

* Shouldn't this be [`PropVal` instead of `Node`](https://github.com/Checkfront/react-storybook-addon-chapters/blob/master/src/components/PropTable.jsx#L3)?

* And this [`newPropTables` instead of `propTables`](https://github.com/Checkfront/react-storybook-addon-chapters/blob/master/src/components/Section.jsx#L267)?

When I change both names the prop table renders but I'm not sure if I miss sth here.

**Comment by brandonellis** [comment]
Thanks for this @stephanschubert looks like a few minor bugs from the migration to Storybook 4!
