### ISSUE TITLE
Storybook 5 support?

### ISSUE THREAD

**Issue by willdurand** [Checkfront/react-storybook-addon-chapters#48]
Hi,

Storybook released a new major version (5.0) and there are a few breaking changes. I am not sure if this add-on would work out of the box but it requires Storybook 4 currently, which conflicts with Storybook 5 (it compiles but there are errors due to different versions of Storybook installed).

Is there any plan to support Storybook 5 by chance? Thanks!

**Comment by mundosk8** [comment]
I opened a pull request to solve this: https://github.com/Checkfront/react-storybook-addon-chapters/pull/49

**Comment by brandonellis** [comment]
Merged and part of version 3.1.1
