### ISSUE TITLE
Invalid PropTypes definitions

### ISSUE THREAD

**Issue by vvanmol** [Checkfront/react-storybook-addon-chapters#51]
Hello,

After migrating our Storybook to v5, we started to get Warnings in the Web Browser's console looking like this:

`Warning: Invalid argument supplied to oneOfType, expected an instance of array.`

After debugging it seems the Warnings are coming from this package, more especially the PropType definitions of `Story`, `Chapter` and `Section`.

In all 3 of these Components, the following PropTypes are defined:

```javascript
  title: PropTypes.oneOfType(PropTypes.string, PropTypes.object),
  subtitle: PropTypes.oneOfType(PropTypes.string, PropTypes.object),
```

According to React PropType documentation, `oneOfType` takes an array as Parameter.  Therefore, the above PropTypes should be updated to the following in all 3 Components:

```javascript
  title: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  subtitle: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
```

**Comment by brandonellis** [comment]
Version 3.1.3 takes care of this.  Thank you for the note.
